#! /bin/bash

./bin/khatus \
    --dir_bin ./bin \
    --wifi_interface wlp4s0 \
    --screen_brightness_device_name intel_backlight \
| stdbuf -o L tee \
    >(stdbuf -o L ./bin/khatus_bar \
        -v Opt_Mpd_Song_Max_Chars=10 \
        -v Opt_Pulseaudio_Sink=0 \
        -v GC_Interval=300 \
        -f <(./bin/khatus_gen_bar_make_status \
                -v Status_Fmt=' E=%s%% M=%d%% P=[%s %sr %sd %st %si %sz] C=[%s %s°C %srpm] D=[%s%% %s▲ %s▼] W=[%s %s▲ %s▼] B=%s *=%s%% (%s) [%s] %s°F %s ' \
                -v Status_Args='@energy_percent,@memory_percent,@processes_count_all,@processes_count_r,@processes_count_d,@processes_count_t,@processes_count_i,@processes_count_z,@cpu_loadavg,@cpu_temp,@cpu_fan_speed,@disk_space,@disk_io_w,@disk_io_r,@net_wifi:wlp4s0,@net_io_w:wlp4s0,@net_io_r:wlp4s0,@bluetooth_power,@backlight_percent,@volume:0,@mpd,@weather_temp_f,@datetime' \
            ) \
    ) \
    >(stdbuf -o L ./bin/khatus_cache_dumper $(hostname) 5 "$PWD/data") \
    >(stdbuf -o L ./bin/khatus_monitor_energy) \
    >(stdbuf -o L ./bin/khatus_monitor_errors) \
    >(stdbuf -o L ./bin/khatus_monitor_devices) \
    >(stdbuf -o L ./bin/khatus_actuate_device_add_to_automount \
        -v Execute_On_Mount=thunar \
    ) \
> /dev/null
