#! /bin/bash

./bin/khatus \
    --dir_bin ./bin \
    --wifi_interface wlp3s0 \
| stdbuf -o L tee \
    >(stdbuf -o L ./bin/khatus_bar \
        -v Opt_Mpd_Song_Max_Chars=10 \
        -v Opt_Net_Interfaces_To_Show=wlp3s0 \
        -v Opt_Pulseaudio_Sink=0 \
        -v GC_Interval=300 \
    ) \
    >(stdbuf -o L ./bin/khatus_monitor_energy) \
    >(stdbuf -o L ./bin/khatus_monitor_errors) \
    >(stdbuf -o L ./bin/khatus_monitor_devices) \
    >(stdbuf -o L ./bin/khatus_actuate_device_add_to_automount) \
> /dev/null
