#! /bin/bash

./bin/khatus \
    --dir_bin ./bin \
    --wifi_interface wlp3s0 \
| stdbuf -o L tee \
    >(stdbuf -o L ./bin/khatus_bar \
        -v Opt_Mpd_Song_Max_Chars=10 \
        -v Opt_Net_Interfaces_To_Show=wlp3s0 \
        -v Opt_Pulseaudio_Sink=0 \
        -v GC_Interval=300 \
        -f <(./bin/khatus_gen_bar_make_status \
                -v Status_Bar='@energy,@memory,@processes,@cpu,@disk,@net,@bluetooth,@backlight,@volume,@mpd,@weather,@datetime' \
            ) \
    ) \
    >(stdbuf -o L ./bin/khatus_monitor_energy) \
    >(stdbuf -o L ./bin/khatus_monitor_errors) \
    >(stdbuf -o L ./bin/khatus_monitor_devices) \
    >(stdbuf -o L ./bin/khatus_actuate_device_add_to_automount \
        -v Execute_On_Mount=thunar \
    ) \
> /dev/null
