#! /bin/sh

set -e

. ./bin/khatus_x4_lib_common_sensor.sh

dir="${prefix}/${host}"

sensors_kill_all() {
    for pid_file in $(find $dir -type f -name pid)
    do
        kill -9 $(cat $pid_file) || true
        rm $pid_file
    done
    pkill khatus_x4 || true
}

sensors_fork_all() {
    ./bin/khatus_x4_sensor_datetime  -d -i 1
    ./bin/khatus_x4_sensor_bluetooth -d -i 1
    ./bin/khatus_x4_sensor_mpd       -d -i 1
    ./bin/khatus_x4_sensor_energy    -d -i 1
    ./bin/khatus_x4_sensor_memory    -d -i 1
    ./bin/khatus_x4_sensor_loadavg   -d -i 1
    ./bin/khatus_x4_sensor_temp      -d -i 1 -- -z 0
    ./bin/khatus_x4_sensor_disk      -d -i 1 -- -f /
    ./bin/khatus_x4_sensor_volume    -d -i 1
}

sensor_read_one() {
    if test -f "$1"
    then
        cat "$1"
    else
        printf '%s\n' '--'
    fi
}

sensors_read_all() {
    while :
    do
        battery_state="$(sensor_read_one ${dir}/khatus_x4_sensor_energy/out/battery_state)"
        battery_percentage="$(sensor_read_one ${dir}/khatus_x4_sensor_energy/out/battery_percentage)"
        bluetooth_controllers="$(sensor_read_one ${dir}/khatus_x4_sensor_bluetooth/out/count_powered_controllers)"
        bluetooth_devices="$(sensor_read_one ${dir}/khatus_x4_sensor_bluetooth/out/count_connected_devices)"
        datetime="$(sensor_read_one ${dir}/khatus_x4_sensor_datetime/out/datetime)"
        mpd="$(sensor_read_one ${dir}/khatus_x4_sensor_mpd/out/status)"
        mem="$(sensor_read_one ${dir}/khatus_x4_sensor_memory/out/percent_used)"
        load="$(sensor_read_one ${dir}/khatus_x4_sensor_loadavg/out/load_avg_1min)"
        temp="$(sensor_read_one ${dir}/khatus_x4_sensor_temp/out/thermal_zone0)"
        disk="$(sensor_read_one ${dir}/khatus_x4_sensor_disk/out/disk_usage_percentage)"
        vol_left="$(sensor_read_one ${dir}/khatus_x4_sensor_volume/out/vol_left)"
        vol_right="$(sensor_read_one ${dir}/khatus_x4_sensor_volume/out/vol_right)"
        vol_state="$(sensor_read_one ${dir}/khatus_x4_sensor_volume/out/state)"
        vol_mute="$(sensor_read_one ${dir}/khatus_x4_sensor_volume/out/mute)"
        echo "E[${battery_state} ${battery_percentage}] M:${mem}% L:${load} T:${temp}°C D:${disk}% [${mpd}] [$bluetooth_controllers $bluetooth_devices] V:${vol_state}:${vol_left}:${vol_right}:${vol_mute} ${datetime}"
        sleep 1
    done
}

main() {
    sensors_kill_all
    sensors_fork_all
    sensors_read_all
}

main
