#! /bin/sh

set -e

. ./bin/khatus_x4_lib_common_sensor.sh

dir="${prefix}/${host}"

sensors_kill_all() {
    for pid_file in $(find $dir -type f -name pid)
    do
        kill -9 $(cat $pid_file) || true
        rm $pid_file
    done
    pkill khatus_x4_sensor || true
}

sensors_fork_all() {
    ./bin/khatus_x4_sensor_datetime &
    ./bin/khatus_x4_sensor_bluetooth&
    ./bin/khatus_x4_sensor_mpd      &
    ./bin/khatus_x4_sensor_energy   &
    ./bin/khatus_x4_sensor_memory   &
}

sensor_read_one() {
    if test -f "$1"
    then
        cat "$1"
    else
        printf '%s\n' '--'
    fi
}

sensors_read_all() {
    while :
    do
        battery_state="$(sensor_read_one ${dir}/khatus_x4_sensor_energy/out/battery_state)"
        battery_percentage="$(sensor_read_one ${dir}/khatus_x4_sensor_energy/out/battery_percentage)"
        bluetooth_controllers="$(sensor_read_one ${dir}/khatus_x4_sensor_bluetooth/out/count_powered_controllers)"
        bluetooth_devices="$(sensor_read_one ${dir}/khatus_x4_sensor_bluetooth/out/count_connected_devices)"
        datetime="$(sensor_read_one ${dir}/khatus_x4_sensor_datetime/out/datetime)"
        mpd="$(sensor_read_one ${dir}/khatus_x4_sensor_mpd/out/status)"
        mem="$(sensor_read_one ${dir}/khatus_x4_sensor_memory/out/percent_used)"
        echo "E[${battery_state} ${battery_percentage}] M:${mem}% [${mpd}] [$bluetooth_controllers $bluetooth_devices] ${datetime}"
        sleep 1
    done
}

main() {
    sensors_kill_all
    sensors_fork_all
    sensors_read_all
}

main
